// AUTO-GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by StatSystemCodeGenerator
// Generated on: 2026-01-02 21:45:38
// To regenerate: Tools → NinjaGame → Regenerate Stat Properties

using UnityEngine;

/// <summary>
/// Auto-generated property accessors for StatSystem.
/// Provides type-safe, IntelliSense-friendly access to stats.
/// </summary>
public partial class StatSystem
{
    /// <summary>
    /// Physical damage reduction
    /// Source: RPGCombatStats
    /// </summary>
    public float Armor
    {
        get => GetValue("combat.armor");
        set => SetBaseValue("combat.armor", value);
    }

    /// <summary>
    /// Bonus damage added to attacks
    /// Source: RPGCombatStats
    /// </summary>
    public float AttackPower
    {
        get => GetValue("combat.attack_power");
        set => SetBaseValue("combat.attack_power", value);
    }

    /// <summary>
    /// Physical strength and power
    /// Source: RPGCoreStats
    /// </summary>
    public float Body
    {
        get => GetValue("character.body");
        set => SetBaseValue("character.body", value);
    }

    /// <summary>
    /// Chance to land critical hits (%)
    /// Source: RPGCombatStats
    /// </summary>
    public float CritChance
    {
        get => GetValue("combat.crit_chance");
        set => SetBaseValue("combat.crit_chance", value);
    }

    /// <summary>
    /// Critical hit damage multiplier
    /// Source: RPGCombatStats
    /// </summary>
    public float CritDamage
    {
        get => GetValue("combat.crit_damage");
        set => SetBaseValue("combat.crit_damage", value);
    }

    /// <summary>
    /// Vitality and stamina
    /// Source: RPGCoreStats
    /// </summary>
    public float Endurance
    {
        get => GetValue("character.endurance");
        set => SetBaseValue("character.endurance", value);
    }

    /// <summary>
    /// Wisdom and perception
    /// Source: RPGCoreStats
    /// </summary>
    public float Insight
    {
        get => GetValue("character.insight");
        set => SetBaseValue("character.insight", value);
    }

    /// <summary>
    /// Maximum hit points
    /// Source: RPGResources
    /// </summary>
    public float MaxHealth
    {
        get => GetValue("character.max_health");
        set => SetBaseValue("character.max_health", value);
    }

    /// <summary>
    /// Maximum mana
    /// Source: RPGResources
    /// </summary>
    public float MaxMana
    {
        get => GetValue("character.max_mana");
        set => SetBaseValue("character.max_mana", value);
    }

    /// <summary>
    /// Maximum stamina
    /// Source: RPGResources
    /// </summary>
    public float MaxStamina
    {
        get => GetValue("character.max_stamina");
        set => SetBaseValue("character.max_stamina", value);
    }

    /// <summary>
    /// Intelligence and magical power
    /// Source: RPGCoreStats
    /// </summary>
    public float Mind
    {
        get => GetValue("character.mind");
        set => SetBaseValue("character.mind", value);
    }

    /// <summary>
    /// Defense and damage reduction
    /// Source: RPGCoreStats
    /// </summary>
    public float Resilience
    {
        get => GetValue("character.resilience");
        set => SetBaseValue("character.resilience", value);
    }

    /// <summary>
    /// Agility and dexterity
    /// Source: RPGCoreStats
    /// </summary>
    public float Spirit
    {
        get => GetValue("character.spirit");
        set => SetBaseValue("character.spirit", value);
    }

}
